### PR TITLE
Fix up navigation pull down

### PR DESCRIPTION
**Pull request by neomorphic**
The button on the navigation bar now has the text to state its'
intention and the button to show the navigation is now thei same color
as the hidden navigation to tie them together and to make it stand out
on black, white, and drab green color backgrounds.

### CODE REVIEW

**Comment by hubbardp** [comment]
My only concern is that "navigation" in the "HIDE NAVIGATION" text on the control seems a bit unclear to me.  I guess choosing the workspace is not what I would have considered to be "navigation", and I wonder if others might be confused.

**Comment by neomorphic** [comment]
@hubbardp your concern seems reasonable. Do you have an alternative noun?

**Comment by hubbardp** [comment]
I almost think just "HIDE" would work.

**Comment by neomorphic** [comment]
I have these:
"HIDE HUB HEADER"
"FULLSCREEN"

**Comment by hubbardp** [comment]
"HIDE HUB HEADER" sounds a bit like it's trying to be cute.  How about just "HIDE HEADER"?

**Comment by hubbardp** [comment]
Looks good to me.  I say go ahead and merge it.

**Pull request merged**
